/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.nodes;

/**
 *
 * @author gabri
 */
public class SimpleNode extends javax.swing.JPanel {

    public void setNextNode(SimpleNode node) {
        this.nextNode = node;
    }
    
    public SimpleNode getNextNode(){
        return nextNode;
    }
    
    public String getValue(){
        return value;
    }
    
    public void setValue(String s){
        this.value = s;
        content.setText(s);
    }

    /**
     * Creates new form SimpleNode
     */
    public SimpleNode(String value) {
        initComponents();
        content.setText(value);
        this.value = value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 73, 164));
        setName("node"); // NOI18N
        setPreferredSize(new java.awt.Dimension(50, 40));

        content.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        content.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private SimpleNode nextNode;
    private String value;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel content;
    // End of variables declaration//GEN-END:variables
}
