/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gui;

import app.nodes.SimpleNode;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Sequential_list extends javax.swing.JPanel {

    /**
     * Creates new form Lists
     */
    public Sequential_list() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workspace = new javax.swing.JDesktopPane();
        main_panel = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        value_area_1 = new javax.swing.JTextField();
        position_area_1 = new javax.swing.JTextField();
        value_text_1 = new javax.swing.JLabel();
        position_text_1 = new javax.swing.JLabel();
        separator_1 = new javax.swing.JLabel();
        remove_button = new javax.swing.JButton();
        value_area_2 = new javax.swing.JTextField();
        separator_2 = new javax.swing.JLabel();
        get_button = new javax.swing.JButton();
        bar = new javax.swing.JLabel();
        head_info = new javax.swing.JLabel();
        size_info = new javax.swing.JLabel();
        head_text = new javax.swing.JLabel();
        size_text = new javax.swing.JLabel();
        operator = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(898, 720));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/add_icon.png"))); // NOI18N
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        value_area_1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        value_area_1.setForeground(new java.awt.Color(163, 73, 164));

        position_area_1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        position_area_1.setForeground(new java.awt.Color(163, 73, 164));
        position_area_1.setToolTipText("");

        value_text_1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        value_text_1.setForeground(new java.awt.Color(163, 73, 164));
        value_text_1.setText("Valor:");

        position_text_1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        position_text_1.setForeground(new java.awt.Color(163, 73, 164));
        position_text_1.setText("Posição:");

        separator_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/vertical_bar.png"))); // NOI18N

        remove_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/remove_icon.png"))); // NOI18N
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        value_area_2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        value_area_2.setForeground(new java.awt.Color(163, 73, 164));

        separator_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/vertical_bar.png"))); // NOI18N

        get_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/get_icon.png"))); // NOI18N

        bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/bar.png"))); // NOI18N

        head_info.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        head_info.setForeground(new java.awt.Color(163, 73, 164));
        head_info.setText("N");

        size_info.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        size_info.setForeground(new java.awt.Color(163, 73, 164));
        size_info.setText("0");

        head_text.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        head_text.setForeground(new java.awt.Color(163, 73, 164));
        head_text.setText("Cabeça:");

        size_text.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        size_text.setForeground(new java.awt.Color(163, 73, 164));
        size_text.setText("Tamanho:");

        operator.setBackground(new java.awt.Color(163, 73, 164));
        operator.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        operator.setForeground(new java.awt.Color(163, 73, 164));
        operator.setText("Posição:");
        operator.setContentAreaFilled(false);
        operator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        operator.setMaximumSize(new java.awt.Dimension(70, 27));
        operator.setMinimumSize(new java.awt.Dimension(70, 27));
        operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(position_text_1)
                            .addComponent(value_text_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(value_area_1)
                            .addComponent(position_area_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(separator_1)
                        .addGap(18, 18, 18)
                        .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(value_area_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separator_2)
                        .addGap(18, 18, 18)
                        .addComponent(get_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(size_text)
                            .addComponent(head_text))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(size_info)
                            .addComponent(head_info))))
                .addGap(59, 59, 59))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(value_area_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(get_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(separator_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(main_panelLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(value_area_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(value_text_1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(position_area_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(position_text_1)))
                                .addComponent(separator_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(remove_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size_text)
                            .addComponent(size_info))
                        .addGap(10, 10, 10)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(head_text)
                            .addComponent(head_info))))
                .addGap(23, 23, 23)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        workspace.setLayer(main_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout workspaceLayout = new javax.swing.GroupLayout(workspace);
        workspace.setLayout(workspaceLayout);
        workspaceLayout.setHorizontalGroup(
            workspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        workspaceLayout.setVerticalGroup(
            workspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workspaceLayout.createSequentialGroup()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workspace, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(workspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorActionPerformed
        if (operator.getText().equals("Posição:")) {
            operator.setText("Valor:");
        } else {
            operator.setText("Posição:");
        }
    }//GEN-LAST:event_operatorActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        if (size == 0) {
            JOptionPane.showMessageDialog(null, "Lista Vazia!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (value_area_2.getText().equals("")) {
            deleteEnd();
        } else if (!(value_area_2.getText().equals("")) && operator.getText().equals("Posição:")) {
            if (Integer.parseInt(value_area_2.getText()) > size) {
                JOptionPane.showMessageDialog(null, "Posição Inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            deletePosition(Integer.parseInt(value_area_2.getText()));
        } else if (!(value_area_2.getText().equals("")) && operator.getText().equals("Valor:")) {
            deleteValue(value_area_2.getText());
        }
        head_info.setText(nodes[0].getValue());
        nodes[0].setBackground(Color.red);
        if(size == 0){
            nodes[0].setBackground(nodes[1].getBackground());
        }
        size_info.setText("" + size);
    }//GEN-LAST:event_remove_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        if (nodes == null) {
            createList(Integer.parseInt(JOptionPane.showInputDialog(null, "Entre com o tamanho da lista:", "Aviso", JOptionPane.INFORMATION_MESSAGE)));
            return;
        }
        if(size == nodes.length){
            JOptionPane.showMessageDialog(null, "Lista cheia!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (value_area_1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de Valor não pode ficar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (position_area_1.getText().equals("") && !(value_area_1.getText().equals(""))) {
            addEnd(value_area_1.getText());
        } else if (!(position_area_1.getText().equals("")) && !(value_area_1.getText().equals(""))) {
            if (Integer.parseInt(position_area_1.getText()) > size) {
                JOptionPane.showMessageDialog(null, "Valor Inválido", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            addInPosition(value_area_1.getText(), Integer.parseInt(position_area_1.getText()));
        }
        head_info.setText(nodes[0].getValue());
        nodes[0].setBackground(Color.red);
        size_info.setText("" + size);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        reset();
    }//GEN-LAST:event_formFocusLost

    public void deleteValue(String value) {
        for (int i = 0; i < size; i++) {
            if (nodes[i].getValue().equals(value)) {
                deletePosition(i + 1);
                break;
            }
        }
        size--;
    }

    public void deleteEnd() {
        nodes[size - 1].setValue("N");
        size--;
    }

    public void deletePosition(int pos) {
        String aux2;
        for (int i = pos; i < size; i++) {
            aux2 = nodes[i].getValue();
            nodes[i - 1].setValue(aux2);
        }
        nodes[size - 1].setValue("N");
        size--;
    }

    public void addInPosition(String value, int pos) {
        String aux = nodes[pos - 1].getValue();
        String aux2;
        nodes[pos - 1].setValue(value);
        for (int i = pos; i < size; i++) {
            aux2 = nodes[i].getValue();
            nodes[i].setValue(aux);
            aux = aux2;
        }
        size++;
    }

    public void addEnd(String value) {
        nodes[size].setValue(value);
        size++;
    }

    public void createList(int value) {
        this.nodes = new SimpleNode[value];
        this.size = 0;
        for (int i = 0; i < value; i++) {
            nodes[i] = new SimpleNode("N");
            nodes[i].setSize(50, 40);
            nodes[i].setLocation(X, Y);
            workspace.add(nodes[i]);
            nodes[i].setVisible(true);
            X += 55;
        }
    }

    public void reset() {
        removeAll();
        revalidate();
        repaint();
        X = 50;
        Y = 170;
        size = 0;
        nodes = null;
    }

    private int X = 50;
    private int Y = 350;
    private int size;
    private SimpleNode[] nodes;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel bar;
    private javax.swing.JButton get_button;
    private javax.swing.JLabel head_info;
    private javax.swing.JLabel head_text;
    private javax.swing.JPanel main_panel;
    private javax.swing.JButton operator;
    private javax.swing.JTextField position_area_1;
    private javax.swing.JLabel position_text_1;
    private javax.swing.JButton remove_button;
    private javax.swing.JLabel separator_1;
    private javax.swing.JLabel separator_2;
    private javax.swing.JLabel size_info;
    private javax.swing.JLabel size_text;
    private javax.swing.JTextField value_area_1;
    private javax.swing.JTextField value_area_2;
    private javax.swing.JLabel value_text_1;
    private javax.swing.JDesktopPane workspace;
    // End of variables declaration//GEN-END:variables
}
