/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gui;

import app.nodes.SimpleNode;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class stack extends javax.swing.JPanel {

    /**
     * Creates new form Lists
     */
    public stack() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workspace = new javax.swing.JDesktopPane();
        main_panel = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        value_area_1 = new javax.swing.JTextField();
        value_text_1 = new javax.swing.JLabel();
        separator_1 = new javax.swing.JLabel();
        remove_button = new javax.swing.JButton();
        separator_2 = new javax.swing.JLabel();
        get_button = new javax.swing.JButton();
        bar = new javax.swing.JLabel();
        peek_info = new javax.swing.JLabel();
        size_info = new javax.swing.JLabel();
        peek_text = new javax.swing.JLabel();
        size_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(898, 720));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/add_icon.png"))); // NOI18N
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        value_area_1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        value_area_1.setForeground(new java.awt.Color(163, 73, 164));

        value_text_1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        value_text_1.setForeground(new java.awt.Color(163, 73, 164));
        value_text_1.setText("Valor:");

        separator_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/vertical_bar.png"))); // NOI18N

        remove_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/remove_icon.png"))); // NOI18N
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        separator_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/vertical_bar.png"))); // NOI18N

        get_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/get_icon.png"))); // NOI18N
        get_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_buttonActionPerformed(evt);
            }
        });

        bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/bar.png"))); // NOI18N

        peek_info.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        peek_info.setForeground(new java.awt.Color(163, 73, 164));
        peek_info.setText("N");

        size_info.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        size_info.setForeground(new java.awt.Color(163, 73, 164));
        size_info.setText("0");

        peek_text.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        peek_text.setForeground(new java.awt.Color(163, 73, 164));
        peek_text.setText("Topo:");

        size_text.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        size_text.setForeground(new java.awt.Color(163, 73, 164));
        size_text.setText("Tamanho:");

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(value_text_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(value_area_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(separator_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(separator_2)
                        .addGap(18, 18, 18)
                        .addComponent(get_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(size_text)
                            .addComponent(peek_text))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(size_info)
                            .addComponent(peek_info))))
                .addGap(59, 59, 59))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(get_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(separator_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(separator_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(remove_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size_text)
                            .addComponent(size_info))
                        .addGap(10, 10, 10)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peek_text)
                            .addComponent(peek_info)))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(value_text_1)
                            .addComponent(value_area_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        workspace.setLayer(main_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout workspaceLayout = new javax.swing.GroupLayout(workspace);
        workspace.setLayout(workspaceLayout);
        workspaceLayout.setHorizontalGroup(
            workspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        workspaceLayout.setVerticalGroup(
            workspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workspaceLayout.createSequentialGroup()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workspace, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(workspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void get_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get_buttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        if (size == 0) {
            JOptionPane.showMessageDialog(null, "Lista Vazia!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pop();
    }//GEN-LAST:event_remove_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        if (nodes == null) {
            createList(Integer.parseInt(JOptionPane.showInputDialog(null, "Entre com o tamanho da pilha:", "Aviso", JOptionPane.INFORMATION_MESSAGE)));
            return;
        }
        if (size == nodes.length){
            JOptionPane.showMessageDialog(null, "Pilha cheia!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (value_area_1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Valor em branco!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        push(value_area_1.getText());
    }//GEN-LAST:event_add_buttonActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        reset();
    }//GEN-LAST:event_formFocusLost

    public void pop() {
        nodes[size - 1].setValue("N");
        size--;
        if(size == 0){
            nodes[size].setBackground(color);
            peek_info.setText("N");
            size_info.setText("" + size);
            return;
        }
        nodes[size].setBackground(color);
        peek_info.setText(nodes[size - 1].getValue());
        nodes[size - 1].setBackground(Color.red);
        size_info.setText("" + size);
    }

    public void push(String value) {
        nodes[size].setValue(value);
        size++;
        nodes[size - 1].setBackground(Color.red);
        if ((size - 1) != 0) {
            nodes[size - 2].setBackground(color);
        }
        size_info.setText("" + size);
        peek_info.setText(nodes[size - 1].getValue());
    }

    public void createList(int value) {
        this.nodes = new SimpleNode[value];
        this.size = 0;
        X = 400;
        Y = 650;
        for (int i = 0; i < value; i++) {
            nodes[i] = new SimpleNode("N");
            nodes[i].setSize(50, 40);
            nodes[i].setLocation(X, Y);
            workspace.add(nodes[i]);
            nodes[i].setVisible(true);
            Y -= 45;
        }
        this.color = nodes[0].getBackground();
    }

    public void reset() {
        removeAll();
        revalidate();
        repaint();
        X = 50;
        Y = 170;
        size = 0;
        nodes = null;
    }

    private int X = 50;
    private int Y = 170;
    private int size;
    private SimpleNode[] nodes;
    private Color color;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel bar;
    private javax.swing.JButton get_button;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel peek_info;
    private javax.swing.JLabel peek_text;
    private javax.swing.JButton remove_button;
    private javax.swing.JLabel separator_1;
    private javax.swing.JLabel separator_2;
    private javax.swing.JLabel size_info;
    private javax.swing.JLabel size_text;
    private javax.swing.JTextField value_area_1;
    private javax.swing.JLabel value_text_1;
    private javax.swing.JDesktopPane workspace;
    // End of variables declaration//GEN-END:variables
}
